version: "3.9"

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: {}
